package com.supravin.accharger;

/**
 * Created by User on 30-01-2018.
 */

public class ChargePointRequestStrings {

   //public static final String authorizeRequest="{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"AuthorizeRequest\",\"type\":\"object\",\"properties\":{\"idTag\":{\"type\":\"string\",\"maxLength\":20}},\"additionalProperties\":false,\"required\":[\"idTag\"]}";
   //public static final String bootNotification="{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"BootNotificationRequest\",\"type\":\"object\",\"properties\":{\"chargePointVendor\":{\"type\":\"string\",\"maxLength\":20},\"chargePointModel\":{\"type\":\"string\",\"maxLength\":20},\"chargePointSerialNumber\":{\"type\":\"string\",\"maxLength\":25},\"chargeBoxSerialNumber\":{\"type\":\"string\",\"maxLength\":25},\"firmwareVersion\":{\"type\":\"string\",\"maxLength\":50},\"iccid\":{\"type\":\"string\",\"maxLength\":20},\"imsi\":{\"type\":\"string\",\"maxLength\":20},\"meterType\":{\"type\":\"string\",\"maxLength\":25},\"meterSerialNumber\":{\"type\":\"string\",\"maxLength\":25}},\"additionalProperties\":false,\"required\":[\"chargePointVendor\",\"chargePointModel\"]}";
  // public static final String dataTransfer="{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"DataTransferRequest\",\"type\":\"object\",\"properties\":{\"vendorId\":{\"type\":\"string\",\"maxLength\":255},\"messageId\":{\"type\":\"string\",\"maxLength\":50},\"data\":{\"type\":\"string\"}},\"additionalProperties\":false,\"required\":[\"vendorId\"]}";
   public static final String diagnosticsStatusNotification = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"DiagnosticsStatusNotificationRequest\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Idle\",\"Uploaded\",\"UploadFailed\",\"Uploading\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String firmwareStatusNotification = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"FirmwareStatusNotificationRequest\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Downloaded\",\"DownloadFailed\",\"Downloading\",\"Idle\",\"InstallationFailed\",\"Installing\",\"Installed\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   //public static final String heartbeatRequest = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"HeartbeatRequest\",\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}";
   //public static final String  meterValues = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"MeterValuesRequest\",\"type\":\"object\",\"properties\":{\"connectorId\":{\"type\":\"integer\"},\"transactionId\":{\"type\":\"integer\"},\"meterValue\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"timestamp\":{\"type\":\"string\",\"format\":\"date-time\"},\"sampledValue\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"value\":{\"type\":\"string\"},\"context\":{\"type\":\"string\",\"enum\":[\"Interruption.Begin\",\"Interruption.End\",\"Sample.Clock\",\"Sample.Periodic\",\"Transaction.Begin\",\"Transaction.End\",\"Trigger\",\"Other\"]},\"format\":{\"type\":\"string\",\"enum\":[\"Raw\",\"SignedData\"]},\"measurand\":{\"type\":\"string\",\"enum\":[\"Energy.Active.Export.Register\",\"Energy.Active.Import.Register\",\"Energy.Reactive.Export.Register\",\"Energy.Reactive.Import.Register\",\"Energy.Active.Export.Interval\",\"Energy.Active.Import.Interval\",\"Energy.Reactive.Export.Interval\",\"Energy.Reactive.Import.Interval\",\"Power.Active.Export\",\"Power.Active.Import\",\"Power.Offered\",\"Power.Reactive.Export\",\"Power.Reactive.Import\",\"Power.Factor\",\"Current.Import\",\"Current.Export\",\"Current.Offered\",\"Voltage\",\"Frequency\",\"Temperature\",\"SoC\",\"RPM\"]},\"phase\":{\"type\":\"string\",\"enum\":[\"L1\",\"L2\",\"L3\",\"N\",\"L1-N\",\"L2-N\",\"L3-N\",\"L1-L2\",\"L2-L3\",\"L3-L1\"]},\"location\":{\"type\":\"string\",\"enum\":[\"Cable\",\"EV\",\"Inlet\",\"Outlet\",\"Body\"]},\"unit\":{\"type\":\"string\",\"enum\":[\"Wh\",\"kWh\",\"varh\",\"kvarh\",\"W\",\"kW\",\"VA\",\"kVA\",\"var\",\"kvar\",\"A\",\"V\",\"K\",\"Celcius\",\"Fahrenheit\",\"Percent\"]}},\"required\":[\"value\"]}}},\"required\":[\"timestamp\",\"sampledValue\"]}}},\"additionalProperties\":false,\"required\":[\"connectorId\",\"meterValue\"]}";
  // public static final String startTransaction = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"StartTransactionRequest\",\"type\":\"object\",\"properties\":{\"connectorId\":{\"type\":\"integer\"},\"idTag\":{\"type\":\"string\",\"maxLength\":20},\"meterStart\":{\"type\":\"integer\"},\"reservationId\":{\"type\":\"integer\"},\"timestamp\":{\"type\":\"string\",\"format\":\"date-time\"}},\"additionalProperties\":false,\"required\":[\"connectorId\",\"idTag\",\"meterStart\",\"timestamp\"]}";
   public static final String statusNotification = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"StatusNotificationRequest\",\"type\":\"object\",\"properties\":{\"connectorId\":{\"type\":\"integer\"},\"errorCode\":{\"type\":\"string\",\"enum\":[\"ConnectorLockFailure\",\"EVCommunicationError\",\"GroundFailure\",\"HighTemperature\",\"InternalError\",\"LocalListConflict\",\"NoError\",\"OtherError\",\"OverCurrentFailure\",\"PowerMeterFailure\",\"PowerSwitchFailure\",\"ReaderFailure\",\"ResetFailure\",\"UnderVoltage\",\"OverVoltage\",\"WeakSignal\"]},\"info\":{\"type\":\"string\",\"maxLength\":50},\"status\":{\"type\":\"string\",\"enum\":[\"Available\",\"Preparing\",\"Charging\",\"SuspendedEVSE\",\"SuspendedEV\",\"Finishing\",\"Reserved\",\"Unavailable\",\"Faulted\"]},\"timestamp\":{\"type\":\"string\",\"format\":\"date-time\"},\"vendorId\":{\"type\":\"string\",\"maxLength\":255},\"vendorErrorCode\":{\"type\":\"string\",\"maxLength\":50}},\"additionalProperties\":false,\"required\":[\"connectorId\",\"errorCode\",\"status\"]}";
  // public static final String stopTransaction = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"StopTransactionRequest\",\"type\":\"object\",\"properties\":{\"idTag\":{\"type\":\"string\",\"maxLength\":20},\"meterStop\":{\"type\":\"integer\"},\"timestamp\":{\"type\":\"string\",\"format\":\"date-time\"},\"transactionId\":{\"type\":\"integer\"},\"reason\":{\"type\":\"string\",\"enum\":[\"EmergencyStop\",\"EVDisconnected\",\"HardReset\",\"Local\",\"Other\",\"PowerLoss\",\"Reboot\",\"Remote\",\"SoftReset\",\"UnlockCommand\",\"DeAuthorized\"]},\"transactionData\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"timestamp\":{\"type\":\"string\",\"format\":\"date-time\"},\"sampledValue\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"value\":{\"type\":\"string\"},\"context\":{\"type\":\"string\",\"enum\":[\"Interruption.Begin\",\"Interruption.End\",\"Sample.Clock\",\"Sample.Periodic\",\"Transaction.Begin\",\"Transaction.End\",\"Trigger\",\"Other\"]},\"format\":{\"type\":\"string\",\"enum\":[\"Raw\",\"SignedData\"]},\"measurand\":{\"type\":\"string\",\"enum\":[\"Energy.Active.Export.Register\",\"Energy.Active.Import.Register\",\"Energy.Reactive.Export.Register\",\"Energy.Reactive.Import.Register\",\"Energy.Active.Export.Interval\",\"Energy.Active.Import.Interval\",\"Energy.Reactive.Export.Interval\",\"Energy.Reactive.Import.Interval\",\"Power.Active.Export\",\"Power.Active.Import\",\"Power.Offered\",\"Power.Reactive.Export\",\"Power.Reactive.Import\",\"Power.Factor\",\"Current.Import\",\"Current.Export\",\"Current.Offered\",\"Voltage\",\"Frequency\",\"Temperature\",\"SoC\",\"RPM\"]},\"phase\":{\"type\":\"string\",\"enum\":[\"L1\",\"L2\",\"L3\",\"N\",\"L1-N\",\"L2-N\",\"L3-N\",\"L1-L2\",\"L2-L3\",\"L3-L1\"]},\"location\":{\"type\":\"string\",\"enum\":[\"Cable\",\"EV\",\"Inlet\",\"Outlet\",\"Body\"]},\"unit\":{\"type\":\"string\",\"enum\":[\"Wh\",\"kWh\",\"varh\",\"kvarh\",\"W\",\"kW\",\"VA\",\"kVA\",\"var\",\"kvar\",\"A\",\"V\",\"K\",\"Celcius\",\"Fahrenheit\",\"Percent\"]}},\"required\":[\"value\"]}}},\"required\":[\"timestamp\",\"sampledValue\"]}}},\"additionalProperties\":false,\"required\":[\"transactionId\",\"timestamp\",\"meterStop\"]}";






}
