package com.supravin.accharger;

/**
 * Created by User on 30-01-2018.
 */

public class ChargePointResponseStrings {

   public static final String cancelReservation = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"CancelReservationResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String changeAvailability ="{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ChangeAvailabilityResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\",\"Scheduled\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String changeConfiguration = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ChangeConfigurationResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\",\"RebootRequired\",\"NotSupported\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String clearCache = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ClearCacheResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String clearChargingProfile = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ClearChargingProfileResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Unknown\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String dataTransfer = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"DataTransferResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\",\"UnknownMessageId\",\"UnknownVendorId\"]},\"data\":{\"type\":\"string\"}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String getCompositeSchedule = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"GetCompositeScheduleResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\"]},\"connectorId\":{\"type\":\"integer\"},\"scheduleStart\":{\"type\":\"string\",\"format\":\"date-time\"},\"chargingSchedule\":{\"type\":\"object\",\"properties\":{\"duration\":{\"type\":\"integer\"},\"startSchedule\":{\"type\":\"string\",\"format\":\"date-time\"},\"chargingRateUnit\":{\"type\":\"string\",\"enum\":[\"A\",\"W\"]},\"chargingSchedulePeriod\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"startPeriod\":{\"type\":\"integer\"},\"limit\":{\"type\":\"number\",\"multipleOf\":0.1},\"numberPhases\":{\"type\":\"integer\"}},\"required\":[\"startPeriod\",\"limit\"]}},\"minChargingRate\":{\"type\":\"number\",\"multipleOf\":0.1}},\"required\":[\"chargingRateUnit\",\"chargingSchedulePeriod\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String getConfiguration = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"GetConfigurationResponse\",\"type\":\"object\",\"properties\":{\"configurationKey\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"key\":{\"type\":\"string\",\"maxLength\":50},\"readonly\":{\"type\":\"boolean\"},\"value\":{\"type\":\"string\",\"maxLength\":500}},\"required\":[\"key\",\"readonly\"]}},\"unknownKey\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":50}}},\"additionalProperties\":false}";
   public static final String getDiagnostics = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"GetDiagnosticsResponse\",\"type\":\"object\",\"properties\":{\"fileName\":{\"type\":\"string\",\"maxLength\":255}},\"additionalProperties\":false}";
   public static final String getLocalListVersion = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"GetLocalListVersionResponse\",\"type\":\"object\",\"properties\":{\"listVersion\":{\"type\":\"integer\"}},\"additionalProperties\":false,\"required\":[\"listVersion\"]}";
   public static final String remoteStartTransaction = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"RemoteStartTransactionResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String remoteStopTransaction = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"RemoteStopTransactionResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String reserveNowResponse = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ReserveNowResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Faulted\",\"Occupied\",\"Rejected\",\"Unavailable\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String resetResponse = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ResetResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String sendLocalListResponse = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"SendLocalListResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Failed\",\"NotSupported\",\"VersionMismatch\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String setChargingProfileResponse = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"SetChargingProfileResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\",\"NotSupported\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String triggerMessageResponse = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"TriggerMessageResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Rejected\",\"NotImplemented\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String unlockConnectorResponse = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"UnlockConnectorResponse\",\"type\":\"object\",\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Unlocked\",\"UnlockFailed\",\"NotSupported\"]}},\"additionalProperties\":false,\"required\":[\"status\"]}";
   public static final String updateFirmwareResponse = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"UpdateFirmwareResponse\",\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}";




}
